POST http://localhost:3036/login
Content-Type: application/json

{
  "email": "teste@gmail.com",
  "password": "Teste123"
}

###

GET  http://localhost:3036/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdGUiLCJpYXQiOjE3MzIyMTgxNDQsImV4cCI6MTczMjIxODE3NH0.uyA6VeNw11pEo4Q1wKHhAFXz8Qy2UhDWYUyMJLxcuEg

###

POST http://localhost:3036/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0ZUBnbWFpbC5jb20iLCJuYW1lIjoidGVzdGUiLCJ1c2VyVHlwZSI6IkRpYXJpc3RhIiwiaWF0IjoxNzMyMjE4MTEwLCJleHAiOjE3MzI4MjI5MTB9.DvPnriReunm4JpqYuYIf3AgcXcIuVc25_8w91CMY9KE"
}

###

DELETE http://localhost:3036/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0ZUBnbWFpbC5jb20iLCJuYW1lIjoidGVzdGUiLCJ1c2VyVHlwZSI6IkRpYXJpc3RhIiwiaWF0IjoxNzMyMjE4MTEwLCJleHAiOjE3MzI4MjI5MTB9.DvPnriReunm4JpqYuYIf3AgcXcIuVc25_8w91CMY9KE"
}
